# Generated by Django 4.2.5 on 2023-10-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=64)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('grad', models.CharField(max_length=64)),
                ('children', models.PositiveIntegerField(default=0)),
                ('is_marie', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employer')),
            ],
        ),
    ]
