# Generated by Django 4.2.5 on 2023-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_employee_slug_employee_impot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='impot',
            new_name='impot_annuel',
        ),
        migrations.AddField(
            model_name='employee',
            name='impot_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
