# Generated by Django 4.2.5 on 2023-10-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_impot_employee_impot_annuel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='impot_annuel',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='impot_mensuel',
        ),
    ]
